---
title: "Tailwind Site"
---
```{r}
#| include = FALSE
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(htmltools)

# All the components are created here
source("components.R")
```

<main class="w-full bg-white">
<article class="prose lg:prose-lg w-full mx-auto mt-8">

# This is a Quarto website.

You can even use R + htmltools to script creation of html elements using `#| results: asis` chunk option. You should also hide your code with `#| echo: false`. I don't here for illustration purposes only.

```{r} 
#| output: asis
div(class="flow-root not-prose", 
  tags$ul(role = "list", class = "-mb-8",
    TimelineListItem(
      circle = Circle(icon_check, bg = "bg-blue-500"),
      item = p(class="text-sm text-gray-500", "Applied to ", a(href="#", class="font-medium text-gray-900", "Front End Developer")),
      date = as.Date("2023-06-15")
    ),
    TimelineListItem(
      circle = Circle(icon_thumb, bg = "bg-green-500"),
      item = p(class="text-sm text-gray-500", "Applied to ", a(href="#", class="font-medium text-gray-900", "Front End Developer")),
      date = as.Date("2024-01-01")
    ),
    TimelineListItem(
      circle = Circle(icon_person, bg = "bg-gray-400"),
      date = as.Date("2024-01-15")
    ),
  )
) 
```

</article>
</main>
